#!/sbin/bash
echo 0x00 > /config/usb_gadget/g1/bDeviceClass; echo 0x00 > /config/usb_gadget/g1/bDeviceSubClass; echo 0x00 > /config/usb_gadget/g1/bDeviceProtocol; echo 1 > /config/usb_gadget/g1/functions/mass_storage.0/lun.0/cdrom; echo 0 > /config/usb_gadget/g1/functions/mass_storage.0/lun.0/ro
rm /config/usb_gadget/g1/configs/b.1/mass_storage.0
sh -c 'echo > /config/usb_gadget/g1/UDC; echo a600000.dwc3 > /config/usb_gadget/g1/UDC' &
echo "Mass storage mode has been successfully deactivated."; sleep 2
